resources:
  - namespace.yaml
  - ../../mongo/
  - ../../redis/
  - ../../backend/
  - ../../frontend/

images:
  - name: paperhunt-backend
    newName: 813562480144.dkr.ecr.eu-north-1.amazonaws.com/paperhunt-backend
    newTag: d8e647d2497fcabd69c7e259f6193ec82f7d394e
  - name: paperhunt-frontend
    newName: 813562480144.dkr.ecr.eu-north-1.amazonaws.com/paperhunt-frontend
    newTag: d8e647d2497fcabd69c7e259f6193ec82f7d394e

patches:
  - path: image-pull-policy.yaml
